In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [14]:
X=pd.read_csv("C:/Users/Nilanjan Das/Downloads/LR_X.csv")

In [15]:
Y=pd.read_csv("C:/Users/Nilanjan Das/Downloads/LR_Y.csv")

In [16]:
X.shape

(1000, 3)

In [17]:
Y.shape

(1000, 1)

In [18]:
ones=np.ones((1000,1))

In [19]:
ones.shape

(1000, 1)

In [20]:
ones[:10]

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [21]:
new_X=np.concatenate((ones,X),axis=1)

In [24]:
print(new_X)

[[1.   0.26 0.08 0.28]
 [1.   0.26 0.52 0.01]
 [1.   0.85 0.6  0.14]
 ...
 [1.   0.88 0.06 0.33]
 [1.   0.28 0.4  0.41]
 [1.   0.94 0.48 0.45]]


In [25]:
new_X.shape

(1000, 4)

In [26]:
res1=np.linalg.inv(np.dot(np.transpose(new_X),new_X))

In [27]:
res1.shape

(4, 4)

In [28]:
res2=np.dot(np.transpose(new_X),Y)
res2.shape

(4, 1)

In [29]:
beta=np.dot(res1,res2)
print(beta)

[[ 1. ]
 [-1.2]
 [ 2.1]
 [ 2.2]]
